# Generated by Django 5.2 on 2025-05-04 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interview',
            options={'ordering': ['scheduled_at']},
        ),
        migrations.RenameField(
            model_name='interview',
            old_name='details',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='interview',
            old_name='interview_date',
            new_name='scheduled_at',
        ),
        migrations.AddField(
            model_name='applicationnote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interview',
            name='duration',
            field=models.PositiveIntegerField(default=60, help_text='Duration in minutes'),
        ),
        migrations.AddField(
            model_name='interview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_type',
            field=models.CharField(choices=[('Phone', 'Phone'), ('Video', 'Video Call'), ('In-Person', 'In-Person'), ('Assessment', 'Assessment'), ('Other', 'Other')], max_length=20),
        ),
    ]
