# Generated by Django 5.2 on 2025-05-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_interviewquestion_practiceanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practiceanswer',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
