# Generated by Django 5.2 on 2025-05-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('facebook', 'Facebook'), ('github', 'GitHub'), ('instagram', 'Instagram'), ('website', 'Website'), ('other', 'Other')], max_length=20),
        ),
    ]
