# Generated by Django 5.2 on 2025-05-04 18:50

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_sociallink_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=users.models.resume_upload_path),
        ),
    ]
