# Generated by Django 5.2 on 2025-05-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_jobseekerprofile_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('jobseeker', 'Job Seeker'), ('company', 'Company')], max_length=10),
        ),
    ]
